# Generated by Django 4.1.7 on 2023-03-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='quiroga', max_length=50),
            preserve_default=False,
        ),
    ]
